name: Simple Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.ssh_host }}
          REMOTE_USER: ${{ secrets.ssh_user }}
          REMOTE_PORT: ${{ secrets.ssh_port }}
          SOURCE: ./
          TARGET: /home/u128827813/domains/test.pearl-developer.com/public_html/aarshinternational

          SCRIPT_AFTER: |
            cd /home/u128827813/domains/test.pearl-developer.com/public_html/aarshinternational
            /opt/alt/php82/usr/bin/php artisan cache:clear
            /opt/alt/php82/usr/bin/php artisan config:clear
            /opt/alt/php82/usr/bin/php artisan route:clear
            /opt/alt/php82/usr/bin/php artisan view:clear
            /opt/alt/php82/usr/bin/php artisan migrate --force
            /opt/alt/php82/usr/bin/php artisan db:seed --class=UserSeeder
            /opt/alt/php82/usr/bin/php artisan storage:link
